---
server:
  addr: 0.0.0.0:9000
  path: /metrics
  web_config: ~

logs:
  level: error
  pretty: false

target:
  engine: http
  file: /var/lib/prometheus-hcloud-sd/output.json
  refresh: 30
  credentials: []

...
