---
kind: Service
apiVersion: v1

metadata:
  name: prometheus-hcloud-sd
  labels:
    app.kubernetes.io/name: prometheus-hcloud-sd
    app.kubernetes.io/component: server

spec:
  selector:
    app.kubernetes.io/name: prometheus-hcloud-sd
    app.kubernetes.io/component: server

  ports:
    - name: http
      port: 9000
      targetPort: http
      protocol: TCP

...
